// <auto-generated />
using System;
using CodingClass_7_3_2019;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodingClass_7_3_2019.Migrations
{
    [DbContext(typeof(CodingClassContext))]
    [Migration("20190721060929_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodingClass_7_3_2019.StudentAccount", b =>
                {
                    b.Property<int>("StudentAccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountDue");

                    b.Property<string>("Duration");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("StudentClassType");

                    b.Property<string>("StudentDateOfBirth");

                    b.Property<int>("StudentDifficultyLevel");

                    b.Property<string>("StudentEmailAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("StudentFirstName");

                    b.Property<string>("StudentLastName");

                    b.Property<int>("TotalClassesEnrolled");

                    b.HasKey("StudentAccountNumber")
                        .HasName("PK_AccountNumber");

                    b.ToTable("StudentAccounts");
                });

            modelBuilder.Entity("CodingClass_7_3_2019.StudentCourseHistory", b =>
                {
                    b.Property<int>("CourseHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber");

                    b.Property<decimal>("Amount");

                    b.Property<string>("ClassesEnrolledFor")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<DateTime>("PaymentMadeDateAndTime");

                    b.Property<int>("PaymentType");

                    b.HasKey("CourseHistoryID")
                        .HasName("PK_CourseHistoryID");

                    b.HasIndex("AccountNumber");

                    b.ToTable("StudentHistory");
                });

            modelBuilder.Entity("CodingClass_7_3_2019.StudentCourseHistory", b =>
                {
                    b.HasOne("CodingClass_7_3_2019.StudentAccount", "account")
                        .WithMany()
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
